# values-staging.yaml for web-app
image:
  repository: khabirhakim/ebanking-frontend
  tag: latest # Overridden by command
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  hosts:
    - host: bank-staging.h4k5.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ebanking-frontend-staging-tls
      hosts:
        - bank-staging.h4k5.net

env:
  API_URL: "https://bank-api-staging.h4k5.net/graphql"
  KEYCLOAK_URL: "https://bank-auth.h4k5.net"
  KEYCLOAK_REALM: "ebanking-realm"
  KEYCLOAK_CLIENT_ID: "ebanking-client"

serviceAccount:
  create: true
  name: web-app-staging
