# values.yaml for ai-assistant-service
replicaCount: 1
fullnameOverride: ai-assistant-service

image:
  repository: ebanking/ai-assistant-service
  tag: local
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8090

env:
  SPRING_PROFILES_ACTIVE: kubernetes
  MONGODB_URI: mongodb://ebanking:ebanking123@ebanking-infra-mongodb:27017/ebanking?authSource=admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: ebanking-infra-kafka-broker:9092
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.ebanking.local/realms/ebanking-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://ebanking-infra-keycloakx-http:80/realms/ebanking-realm/protocol/openid-connect/certs

serviceAccount:
  create: true
  name: ai-assistant-service-microservice
