# values-staging.yaml for graphql-gateway
image:
  repository: khabirhakim/ebanking-graphql-gateway
  tag: latest # Overridden by command
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  hosts:
    - host: bank-api-staging.h4k5.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ebanking-api-staging-tls
      hosts:
        - bank-api-staging.h4k5.net

env:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "ebanking-infra-kafka-broker.ebanking.svc.cluster.local:9092"
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_CLOUD_DISCOVERY_ENABLED: "true"
  SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED: "true"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://bank-auth.h4k5.net/realms/ebanking-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://ebanking-infra-keycloakx-http.ebanking.svc.cluster.local:80/realms/ebanking-realm/protocol/openid-connect/certs

serviceAccount:
  create: true
  name: graphql-gateway-staging
