# values-prod.yaml for audit-service
replicaCount: 1
fullnameOverride: audit-service

image:
  repository: khabirhakim/ebanking-audit-service
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8091

env:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_DATA_MONGODB_URI: "mongodb+srv://mongo_user:pass@ebanking-cluster.9vckujg.mongodb.net/ebanking_db?retryWrites=true&w=majority"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: ebanking-infra-kafka-broker:9092
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://bank-auth.h4k5.net/realms/ebanking-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://ebanking-infra-keycloakx-http:80/realms/ebanking-realm/protocol/openid-connect/certs

serviceAccount:
  create: true
  name: audit-service-microservice

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
