# values-staging.yaml for ai-assistant-service
fullnameOverride: "ai-assistant-service"

image:
  repository: khabirhakim/ebanking-ai-assistant-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8090

env:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_DATA_MONGODB_URI: "mongodb+srv://mongo_user:pass@ebanking-cluster.9vckujg.mongodb.net/staging_db?retryWrites=true&w=majority"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "ebanking-infra-kafka-broker.ebanking.svc.cluster.local:9092"
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://bank-auth.h4k5.net/realms/ebanking-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://ebanking-infra-keycloakx-http.ebanking.svc.cluster.local:80/realms/ebanking-realm/protocol/openid-connect/certs

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "384Mi"
    cpu: "250m"

serviceAccount:
  create: true
  name: ai-assistant-service-staging
