# values-staging.yaml for user-service
image:
  repository: khabirhakim/ebanking-user-service
  tag: latest # Overridden by command
  pullPolicy: Always

env:
  SPRING_PROFILES_ACTIVE: kubernetes
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ebanking-infra-postgresql.ebanking.svc.cluster.local:5432/ebanking_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "ebanking-infra-kafka-broker.ebanking.svc.cluster.local:9092"
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://bank-auth.h4k5.net/realms/ebanking-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://ebanking-infra-keycloakx-http.ebanking.svc.cluster.local:80/realms/ebanking-realm/protocol/openid-connect/certs

extraEnv:
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: password

serviceAccount:
  create: true
  name: user-service-staging
