apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    groupBy: ['job', 'alertname', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack'
  receivers:
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        name: slack-webhook
        key: url
      channel: '#alerts'
      title: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'
      text: '{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}'
